version: "2"
services:
  cassandra:
    image: cassandra
  redis:
    image: redis
  mysql:
    image: mysql:5.6.26
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=jobless
    ports:
      - "6785:3306"
  web:
    image: python:3.5-alpine
    depends_on:
      - mysql
      - redis
    ports:
      - "5453:5453"
    volumes:
      - .:/opt/jobless
    command: /bin/ash -c "pip install -e /opt/jobless && flask run --host=0.0.0.0"
    environment:
      - FLASK_APP=jobless.web.api
      - FLASK_DEBUG=1